-- Find Big Tables and Indexes candidates for partitioning

--PROMPT @script <Schema-Name>

PROMPT PART TABLES COUNT
select count(*) from ALL_TAB_PARTITIONS where TABLE_OWNER='OPERA';


PROMPT CANDIDATE FOR PARTITIONING

set lines 400
col OWNER for a30
col SEGMENT_NAME for a45
col TABLE_NAME for a45
col PARTITIONED for a12

select TBLALL.OWNER,TBLSEGTOP100.TABLE_NAME, TBLSEGTOP100.SIZE_MB, TBLALL.NUM_ROWS, TBLALL.PARTITIONED
from 
(
select OWNER,SEGMENT_NAME "TABLE_NAME",sum(bytes)/1024/1024 "SIZE_MB"
from dba_segments
where SEGMENT_TYPE='TABLE' and OWNER='OPERA'
group by OWNER,SEGMENT_NAME
order by 3 DESC 
FETCH NEXT 100 ROWS ONLY
) TBLSEGTOP100, dba_tables TBLALL
where TBLALL.OWNER=TBLSEGTOP100.OWNER
and  TBLALL.TABLE_NAME=TBLSEGTOP100.TABLE_NAME
and TBLSEGTOP100.SIZE_MB > 10000;